# Generated by Django 4.0 on 2022-01-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=10)),
                ('keyskills', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=30)),
                ('aadharno', models.CharField(max_length=12)),
                ('regdate', models.CharField(max_length=30)),
            ],
        ),
    ]
