# Generated by Django 4.0 on 2022-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('doj', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('panno', models.CharField(max_length=10)),
                ('aadharno', models.CharField(max_length=12)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
